[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace]
resolver = "2"
members = [
    "solutions",
    "web",
    "app"
]

[workspace.dependencies]
anyhow = "1.0.75"
thiserror = "1.0.50"
